server:
  port: 11008
spring:
  application:
    name : tracing
  sleuth:
    enabled: false   

      
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch-zipkin-cluste
      hosts: 106.15.88.220:9200
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
