spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yiping999/springcloud-pig/tree/master/config/src/main/resources/shared
          username: yiping999
          password: yiping897209
          
        #native:
        #  search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}