security:
  oauth2:
    client:
      clientId: customer-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.88.220:3306/test
    username: root
    password: changeit
  jpa:
     show-sql:true
     hibernate:ddl-auto:update
logging:
  level:
    org.springframework.data: DEBUG

server:
  context-path: /customers
  port: 6001

  
